# Generated by Django 4.1.2 on 2022-11-11 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAtencion', models.DateField(max_length=20, verbose_name='Fecha de Atención')),
                ('motivoConsulta', models.CharField(max_length=45, verbose_name='Motivo de la Consulta')),
                ('causasExternas', models.CharField(max_length=45, verbose_name='Causas Externas')),
                ('alergiaMedicamento', models.CharField(max_length=245, verbose_name='Alergia a Medicamento')),
                ('cirugiasRecibidas', models.CharField(max_length=245, verbose_name='Cirugias recibidas')),
                ('tratamientosMedicamentos', models.CharField(max_length=245, verbose_name='Tratamiento o Medicamentos')),
                ('informeYtratamientos', models.CharField(max_length=245, verbose_name='Informe Medico y tratamientos')),
                ('nombresAcompañante', models.CharField(max_length=45, verbose_name='Nombres del Acompañante')),
                ('telAcompañante', models.CharField(max_length=45, verbose_name='Teléfono del Acompañante')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.medico', verbose_name='Medico')),
                ('pacientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.pacientes', verbose_name='Paciente')),
            ],
        ),
    ]
