# Generated by Django 4.1.2 on 2022-11-11 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lugares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombresEspecialidad', models.CharField(max_length=45, verbose_name='Nombres de la Especialidad')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=2, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=45, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=45, verbose_name='Apellidos')),
                ('tipoDocumento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('RC', 'Registro Civil'), ('PP', 'Pasaporte'), ('CE', 'Cédula de Extranjería'), ('OTRO', 'OT')], max_length=45, verbose_name='Tipo de Documento')),
                ('numeroDocumento', models.CharField(max_length=50, verbose_name='Número de documento')),
                ('telefono', models.CharField(max_length=45, verbose_name='Número de Teléfono')),
                ('email', models.CharField(max_length=45, verbose_name='email')),
                ('tipoUsuario', models.CharField(choices=[('Administrador', 'Administrador'), ('Recepcionista', 'Recepcionista')], default='Recepcionista', max_length=13, verbose_name='Tipo de Usuario')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=2, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=45, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=45, verbose_name='Apellidos')),
                ('edad', models.DateField(max_length=45, verbose_name='Edad')),
                ('tipoDocumento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('RC', 'Registro Civil'), ('PP', 'Pasaporte'), ('CE', 'Cédula de Extranjería'), ('OTRO', 'OT')], default='CC', max_length=6, verbose_name='Tipo de Documento')),
                ('numeroDocumento', models.CharField(max_length=50, verbose_name='Número de documento')),
                ('grupoSanguineo', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=20, verbose_name='Grupo Sanguineo')),
                ('direccion', models.CharField(max_length=45, verbose_name='Dirección')),
                ('email', models.CharField(max_length=45, verbose_name='Email')),
                ('telefono', models.CharField(max_length=20, verbose_name='Número de Teléfono')),
                ('estadoCivil', models.CharField(choices=[('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Soltero', 'Soltero'), ('Separado', 'Separado'), ('OTRO', 'OT')], default='OTRO', max_length=10, verbose_name='Estado Civil')),
                ('ocupacion', models.CharField(max_length=100, verbose_name='Ocupación')),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('OTRO', 'OT')], default='OTRO', max_length=4, verbose_name='Genero')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=2, verbose_name='Estado')),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugares.barrio', verbose_name='Barrio')),
                ('eps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugares.eps', verbose_name='EPS')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoMedico', models.CharField(max_length=45, verbose_name='Código de medico')),
                ('tipoDocumento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('RC', 'Registro Civil'), ('PP', 'Pasaporte'), ('CE', 'Cédula de Extranjería'), ('OTRO', 'OT')], default='CC', max_length=6, verbose_name='Tipo de Documento')),
                ('numeroDocumento', models.CharField(max_length=50, verbose_name='Número de documento')),
                ('nombres', models.CharField(max_length=45, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=45, verbose_name='Apellidos')),
                ('telefono', models.CharField(max_length=20, verbose_name='Número de Teléfono')),
                ('email', models.CharField(max_length=45, verbose_name='Email')),
                ('cantServDia', models.CharField(max_length=45, verbose_name='Cantidad de servicios al día')),
                ('cantServMes', models.CharField(max_length=45, verbose_name='Cantidad de servicios al Mes')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=2, verbose_name='Estado')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.especialidad', verbose_name='Especialidad')),
            ],
        ),
    ]
