# Generated by Django 4.1.2 on 2022-11-11 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CiudadResidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoCiudad', models.CharField(max_length=45, verbose_name='Codigo de Ciudad')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre de la ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='EPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEPS', models.CharField(max_length=45, verbose_name='Nombres de la EPS')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=2, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(max_length=45, verbose_name='Localidad')),
                ('nombreLocalidad', models.CharField(max_length=45, verbose_name='Nombres de la Localidad')),
                ('ciudadResidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugares.ciudadresidencia', verbose_name='Ciudad de residencia')),
            ],
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barrio', models.CharField(max_length=45, verbose_name='Nombres del Barrio')),
                ('codigoBarrio', models.CharField(max_length=45, verbose_name='Codigo del Barrio')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=2, verbose_name='Estado')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugares.localidad', verbose_name='Localidad')),
            ],
        ),
    ]
